
version: '3.8'
services:
  postgres:
    image: postgres:17.2
    container_name: postgres_container
    environment:
      POSTGRES_DB: vcipintegration
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password@5432
      POSTGRES_HOST_AUTH_METHOD: trust  
    ports:
      - 5432:5432
    restart: unless-stopped  
    volumes:
      - pg_data:/var/lib/postgresql/data
      # - ./migrations/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      # - ./migrations/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./migrations/entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    networks:
      - pg_network
    # env_file:
    #   - .env      

volumes:
  pg_data:

networks:
  pg_network: